feat: add dependency check in analyse nginx script

diff --git a/scripts/analyse-nginx-log b/scripts/analyse-nginx-log
--- a/scripts/analyse-nginx-log
+++ b/scripts/analyse-nginx-log
@@ -25,6 +25,25 @@ user_agents_with_most_request() {
     awk -F '"' '{ print $6 }' "$LOG_FILE" | sort | uniq -c | head -10
 }
 
+# check if necessary binaries are in PATH
+prerequisites=(
+    awk
+    sort
+    uniq
+    head
+)
+
+proceed=true
+for bin in "${prerequisites[@]}"; do
+    if [[ -z "$(command -v "$bin")" ]]; then
+        echo "$bin not found on the system"
+        proceed=false
+    fi
+done
+if [[ "$proceed" != true ]]; then
+    exit 1
+fi
+
 if [[ ! -f "$LOG_FILE" ]]; then
     echo "file not found: $LOG_FILE"
     exit 1
